[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PersianDevs"
authors = [{name = "PersianDevs", email = "persiandevs.ir@gmail.com"}]
dynamic = ["version", "description"]
